/*Tests interrupts generated by the Hall Effect Sensor 
 * when a magnet passes by.
 * Interrupt routine should ensure the image is always upright.
 * It should also constantly recalibrate the speed.
 * Pin 3 Hall Effect sensor A1344 output pin (Left->Right the pins are: Vcc, Gnd, Output) 
 * 
 */

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
